### ISSUE TITLE
Mod stopped working game marks it as incompatible)

### ISSUE THREAD

**Issue by christian94M** [osldgoth/Enhanced_Map_Colors#27]
Mod stopped working  (game marks it as incompatible)

**Comment by jmklix** [comment]
I fixed it with this pr: https://github.com/osldgoth/Enhanced_Map_Colors/pull/28

It doesn't look like the repo owner has accepted my pr, so in the meantime you can clone my branch if you want this mod in 2.0. I've been running it for weeks without any crashes

**Comment by osldgoth** [comment]
Thanks for updating this! I’m not maintaining this anymore, but it’s great to see people still using the mod after all these years. I’ll merge your changes—appreciate it!
