### ISSUE TITLE
Map Colors do not work help.

### ISSUE THREAD

**Issue by madPav3L** [osldgoth/Enhanced_Map_Colors#5]
Hi,
today I downloaded the mod but it does not work... :(
I am on the latest Factorio experimental version 0.13.13 and the map colors are still the same, see pictures below.
Also if I disable all the other mods and keep only E.M.C. on it still does not work.

![2016-07-31_16-31-44](https://cloud.githubusercontent.com/assets/18511359/17277185/d4253c58-573c-11e6-851b-eaac158c178c.png)
![2016-07-31_16-31-49](https://cloud.githubusercontent.com/assets/18511359/17277186/d42724f0-573c-11e6-803a-359d21585a78.jpg)
![2016-07-31_16-32-40](https://cloud.githubusercontent.com/assets/18511359/17277187/d42bd1b2-573c-11e6-96c7-404ca60156b3.jpg)

**Comment by osldgoth** [comment]
Using the in-game console, type: "/c game.forces.player.rechart()". If that doesn't do it, let me know.

**Comment by madPav3L** [comment]
That did it, thanks!
